name: ${project.name}
description: ${project.description}
main: org.betamc.bmcshield.BMCShield
version: ${project.version}
authors:
  - SvGaming
  - zavdav

commands:
  bmcshield:
    description: Manages the BMCShield kick list.
    usage: /bmcshield
    aliases: [bmcs]
    permission: bmcshield.use