name: ${project.name}
description: ${project.description}
main: org.betamc.bmcshield.BMCShield
version: ${project.version}
authors:
  - SvGaming

commands:
  bmcshield:
    description: A command to add or remove players from the BMCShield list.
    usage: /bmcshield <add/remove/reloadlist> [player]
    aliases: [bmcs]
    permission: bmcshield.bmcshield
    permission-message: You do not have permission to use this command.

permissions:
  bmcshield.*:
    description: Gives access to all myplugin commands.
    children:
      bmcshield.bmcshield: true